adminMenu=xpath=//span[text()='Admin']
addButton=xpath=//button[normalize-space()='Add']
searchUser=xpath=//label[text()='Username']/ancestor::div[contains(@class,'oxd-input-group')]//input
saveButton=xpath=//button[@type='submit']